
import EnumValue = require('dw/value/EnumValue')
import MarkupText = require('dw/content/MarkupText');
import MediaFile = require('dw/content/MediaFile');

// autogeneratedfile - '/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml'
declare global {
    module ICustomAttributes {

		interface OrderAddress {
			/**
			* PayPal Address Status

				valid values are none, confirmed, unconfirmed
			* @group Standard - Standard Address
			* @source [attribute](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#5) | [group](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#33)
			*/
			paypalAddressStatus: string | null;

		}
		interface OrderPaymentInstrument {
			/**
			* PayPal Origination
			* @group PayPal - PayPal
			* @source [attribute](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#40) | [group](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#107)
			*/
			paypalOrigination: string | null;

			/**
			* PayPal Payer ID
			* @group PayPal - PayPal
			* @source [attribute](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#47) | [group](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#103)
			*/
			paypalPayerID: string | null;

			/**
			* PayPal Payer Status

				valid values are verified or unverified
			* @group PayPal - PayPal
			* @source [attribute](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#54) | [group](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#104)
			*/
			paypalPayerStatus: string | null;

			/**
			* PayPal Payment Action
			* @group PayPal - PayPal
			* @source [attribute](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#62) | [group](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#105)
			*/
			paypalPaymentAction: string | null;

			/**
			* PayPal Token
			* @group PayPal - PayPal
			* @source [attribute](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#69) | [group](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#106)
			*/
			paypalToken: string | null;

			/**
			* PayPal Token
			* @group PayPal - PayPal
			* @source [attribute](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#76) | [group](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#106)
			*/
			paypalToken: string | null;

			/**
			* PayPal Transaction ID
			* @group PayPal - PayPal
			* @source [attribute](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#83) | [group](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#101)
			*/
			paypalTransactionID: string | null;

			/**
			* PayPal Auth ID
			* @group PayPal - PayPal
			* @source [attribute](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#90) | [group](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#102)
			*/
			paypalAuthID: string | null;

		}
		interface Profile {
			/**
			* PayPal BAID assigned after Reference Transaction

				Using this ID simplifies the checkout process using reference transactions
			* @group PayPal - PayPal Attributes
			* @source [attribute](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#115) | [group](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#127)
			*/
			PayPalBAID: string | null;

		}
		interface SitePreferences {
			/**
			* PayPal API Password
			* @group PayPal - PayPal Configs
			* @source [attribute](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#133) | [group](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#274)
			*/
			PayPalAPIPassword: string | null;

			/**
			* PayPal API Username
			* @group PayPal - PayPal Configs
			* @source [attribute](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#140) | [group](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#273)
			*/
			PayPalAPIUsername: string | null;

			/**
			* PayPal Button Source Billing
			* @group PayPal - PayPal Configs
			* @source [attribute](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#147) | [group](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#285)
			*/
			PayPalButtonSourceBilling: string | null;

			/**
			* PayPal Button Source Cart
			* @group PayPal - PayPal Configs
			* @source [attribute](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#155) | [group](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#286)
			*/
			PayPalButtonSourceCart: string | null;

			/**
			* PayPal Button Source Direct Payment
			* @group PayPal - PayPal Configs
			* @source [attribute](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#163) | [group](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#287)
			*/
			PayPalButtonSourceDirectPayment: string | null;

			/**
			* PayPal Button Source Review
			* @group PayPal - PayPal Configs
			* @source [attribute](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#171) | [group](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#284)
			*/
			PayPalButtonSourceReview: string | null;

			/**
			* PayPal Cpp Header Image

				Set logo image URL in static mappings as **/logo.jpg s,,,,,/ images/logo.jpg , PayPal limits the logo URL to 127 characters.
Final URL should look like - http://<env>.web.<client>.demandware.net/<logo>.gif
			* @group PayPal - PayPal Configs
			* @source [attribute](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#179) | [group](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#283)
			*/
			PayPalCppHeaderImage: string | null;

			/**
			* PayPal Cpp Headerback Color

				Hex code for the header back color on PayPal pages
			* @group PayPal - PayPal Configs
			* @source [attribute](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#188) | [group](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#280)
			*/
			PayPalCppHeaderbackColor: string | null;

			/**
			* PayPal Cpp Headerborder Color

				Hex code for the header border color on PayPal pages
			* @group PayPal - PayPal Configs
			* @source [attribute](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#196) | [group](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#281)
			*/
			PayPalCppHeaderborderColor: string | null;

			/**
			* PayPal Cpp Payflow Color

				Hex code for the payflow color on PayPal pages
			* @group PayPal - PayPal Configs
			* @source [attribute](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#204) | [group](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#282)
			*/
			PayPalCppPayflowColor: string | null;

			/**
			* PayPal Get Billing Address
			* @group PayPal - PayPal Configs
			* @source [attribute](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#212) | [group](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#279)
			*/
			PayPalGetBillingAddress: boolean | null;

			/**
			* Include Reference Transactions

				This flag indicates if Reference Transactions should be included as part of PayPal login and checkout
			* @group PayPal - PayPal Configs
			* @source [attribute](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#219) | [group](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#288)
			*/
			PayPalIncludeRefTran: boolean | null;

			/**
			* PayPal Mobile User Action Commit

				Commit Mobile transaction on PayPal Side
			* @group PayPal - PayPal Configs
			* @source [attribute](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#226) | [group](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#278)
			*/
			PayPalMobilTransactionCommit: boolean | null;

			/**
			* PayPal Payment Action

				valid values, Authorization, Sale, Order
			* @group PayPal - PayPal Configs
			* @source [attribute](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#233) | [group](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#276)
			*/
			PayPalPaymentAction: string | null;

			/**
			* PayPal Redirect URL

				Redirect URL to Sandbox or Live depends on the environment
			* @group PayPal - PayPal Configs
			* @source [attribute](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#242) | [group](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#277)
			*/
			PayPalRedirectURL: string | null;

			/**
			* PayPal Description Name for Reference Transaction
			* @group PayPal - PayPal Configs
			* @source [attribute](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#251) | [group](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#289)
			*/
			PayPalRefTranDescriptionName: string | null;

			/**
			* PayPal Signature
			* @group PayPal - PayPal Configs
			* @source [attribute](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#258) | [group](file:/Users/anup.raj/Documents/code/NPM_Check_Version/int_paypal/metadata/system-objecttype-extensions.xml#275)
			*/
			PayPalSignature: string | null;

		}
	}
}
